build_in: build
type: img
name: kasm.img
clear_build_path: false
next:
- build: docker
	build_in: docker
	config:
		base_image: kasmweb/api:1.15.0
		image_name: eons/kasm.img
		image_os: debian
		install:
		- postgresql-client
		- wget
		- python3.8-dev
		also:
		- RUN wget -qO /usr/local/bin/yq $(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d '"' -f 4) && chmod +x /usr/local/bin/yq
		- RUN wget -qO- https://github.com/kasmweb-decompilation/api/raw/main/kasm_server.so.gz | gunzip -c > /usr/bin/kasm && chmod +x /usr/bin/kasm
		tags: 
		- "1.15.0"
		- latest
- build: docker_publish
	run_when_any:
	- release
	build_in: publish
	config:
		image_name: eons/kasm.img
